#!/bin/sh
#
# Installation script for Rasbian Wheezy. The installation script can be
# run after compiling the binaries.
#
# Installation:
#
# a) sudo apt-get install sqlite3; sudo apt-get install libsqlite3-dev
#
# b) cd src; make
# 
# c) cd doc; ./mkhtu21d
# 
# d) sudo ./install (this script)
#
# e) create SQLite database table, see table/tables.txt
#
# f) sudo raspi-config (to enable I2C) 
#
# g) sudo service htu21d start
# 
# h) tail -f /var/log/htu21d.log
#
# i) sudo update-rc.d htu21d defaults (optional)
# 
#
# The directories used and files created by this script:
#
# /etc/init.d/htu21d                - init script
# /etc/htu21d_config                - configuration file
# /usr/share/man/man1/htu21d.1      - manual page
# /usr/sbin/htu21d                  - temperature reading daemon
# /var/lib/htu21d/                  - live temperature and humidity data
#
# Sun Nov 30 18:44:58 CET 2014
# Edit: Sun May 17 22:19:28 CEST 2015
# 
# Jaakko Koivuniemi
#


# source directory for 'Htu21d'
SOURCEDIR=${PWD}
SOURCEBIN=${SOURCEDIR}/src
SOURCEMAN=${SOURCEDIR}/doc

# binary executables 
BINDIR=/usr/sbin

# manual pages
MANDIR=/usr/share/man/man1

# init script
INITDIR=/etc/init.d

# for pipicpowerd_conf configuration file
CONFDIR=/etc

# live data 
VARLIBDIR=/var/lib

# binary executables
BINS='htu21d'

if [ -d $SOURCEBIN ]; then
  echo "Copy binary executables to ${BINDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEBIN}/${item} ]; then
       echo "... ${item}"
       /usr/bin/install -C -m 755 ${SOURCEBIN}/${item} ${BINDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEBIN} does not exist"
fi

if [ -d $SOURCEMAN ]; then
  echo "Copy manual pages to ${MANDIR}"
  for item in $BINS;
  do
    if [ -r ${SOURCEMAN}/$item.1 ]; then
       echo "... ${item}.1"
       /usr/bin/install -C -m 664 ${SOURCEMAN}/${item}.1 ${MANDIR}
    fi 
  done
else
  echo "Source directory ${SOURCEMAN} does not exist"
fi

if [ ! -x ${INITDIR}/htu21d ]; then
  echo "Write init script ${INITDIR}/htu21d"
  /usr/bin/install -C -m 755 ${SOURCEDIR}/htu21d.sh ${INITDIR} 
  /bin/mv ${INITDIR}/htu21d.sh ${INITDIR}/htu21d 
else
  echo "Init script ${INITDIR}/htu21d already exists"
fi

if [ ! -r ${CONFDIR}/htu21d_config ]; then
  echo "Write default configuration file ${CONFDIR}/htu21d_config"
  /usr/bin/install -C -m 664 ${SOURCEDIR}/htu21d_config ${CONFDIR} 
else
  echo "Configuration file ${CONFDIR}/htu21d_config already exists" 
fi

if [ -d /var/lib/htu21d ]; then
  echo "Directory /var/lib/htu21d already exists"
else
  echo "Create directory /var/lib/htu21d"
  /bin/mkdir -m 775 /var/lib/htu21d
fi

if /bin/grep -Fxq "i2c-bcm2708" /etc/modules
then
  echo "i2c-bcm2708 found from /etc/modules"
else
  echo "Add i2c-bcm2708 to /etc/modules"
  echo "i2c-bcm2708" >> /etc/modules
fi

if /bin/grep -Fxq "i2c-dev" /etc/modules
then
  echo "i2c-dev found from /etc/modules"
else
  echo "Add i2c-dev to /etc/modules"
  echo "i2c-dev" >> /etc/modules
fi

echo "Run 'update-rc.d htu21d defaults' to automatically start at boot time"
